apiVersion: v1
kind: LimitRange
metadata:
  name: limits-{{TENANT_NAME}}
  namespace: {{TENANT_NAME}}
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "200m"
      memory: "256Mi"
    type: Container
